// ┌───────────────────────────────────────────────────────────────────┐
// │ GENERATED BY FORGE — DO NOT EDIT                                   │
// │ capability: pay.invoices@1.0.0                                    │
// │ template:   slots@1.0.0                                           │
// │ Edits are reported by `forge drift` and will conflict on upgrade.  │
// │ customise via the lineItemFormatting, numberingScheme, paymentTerms slot(s) instead│
// └───────────────────────────────────────────────────────────────────┘

// Re-exports the slot implementations for pay.invoices.
// The stubs themselves are yours; this index is generated from the
// capability's declared slots and updates when it declares a new one.

export { lineItemFormatting } from './lineItemFormatting.js'
export { numberingScheme } from './numberingScheme.js'
export { paymentTerms } from './paymentTerms.js'
