// ┌───────────────────────────────────────────────────────────────────┐
// │ GENERATED BY FORGE — DO NOT EDIT                                   │
// │ capability: kernel.ui@1.0.0                                       │
// │ template:   slots@1.0.0                                           │
// │ Edits are reported by `forge drift` and will conflict on upgrade.  │
// │ customise via the dashboardWidgets, logo, navigationOrder, theme slot(s) instead│
// └───────────────────────────────────────────────────────────────────┘

// Re-exports the slot implementations for kernel.ui.
// The stubs themselves are yours; this index is generated from the
// capability's declared slots and updates when it declares a new one.

export { dashboardWidgets } from './dashboardWidgets.js'
export { logo } from './logo.js'
export { navigationOrder } from './navigationOrder.js'
export { theme } from './theme.js'
