// ┌───────────────────────────────────────────────────────────────────┐
// │ GENERATED BY FORGE — DO NOT EDIT                                   │
// │ capability: kernel.access@1.0.0                                   │
// │ template:   slots@1.0.0                                           │
// │ Edits are reported by `forge drift` and will conflict on upgrade.  │
// │ customise via the permissionResolver, roleDefinitions slot(s) instead│
// └───────────────────────────────────────────────────────────────────┘

// Re-exports the slot implementations for kernel.access.
// The stubs themselves are yours; this index is generated from the
// capability's declared slots and updates when it declares a new one.

export { permissionResolver } from './permissionResolver.js'
export { roleDefinitions } from './roleDefinitions.js'
