// ┌───────────────────────────────────────────────────────────────────┐
// │ GENERATED BY FORGE — DO NOT EDIT                                   │
// │ Derived from the manifest and the resolved capability graph.       │
// │ Edits are reported by `forge drift` and will conflict on upgrade.  │
// │ Change the manifest and re-apply, or `forge eject <path>` to take  │
// │ ownership of this file permanently.                                │
// └───────────────────────────────────────────────────────────────────┘

import { defineConfig } from 'drizzle-kit'

// Migrations are hand-written SQL, reviewed, and shipped by the capability that
// needs them. drizzle-kit is used to inspect and run, never to author: a
// generated diff cannot express a data backfill and cannot be rolled back.
export default defineConfig({
  dialect: 'postgresql',
  schema: './src/generated/kernel.data/entities.ts',
  out: './migrations',
  dbCredentials: { url: process.env.DATABASE_URL! },
})
