// ┌───────────────────────────────────────────────────────────────────┐
// │ GENERATED BY FORGE — DO NOT EDIT                                   │
// │ Derived from the manifest and the resolved capability graph.       │
// │ Edits are reported by `forge drift` and will conflict on upgrade.  │
// │ Change the manifest and re-apply, or `forge eject <path>` to take  │
// │ ownership of this file permanently.                                │
// └───────────────────────────────────────────────────────────────────┘

import type { NextConfig } from 'next'

const config: NextConfig = {
  experimental: { instrumentationHook: true },
  transpilePackages: ["@forge/data-files", "@forge/docs-generation", "@forge/kernel-access", "@forge/kernel-admin", "@forge/kernel-audit", "@forge/kernel-data", "@forge/kernel-events", "@forge/kernel-identity", "@forge/kernel-mail", "@forge/kernel-money", "@forge/kernel-observability", "@forge/kernel-ui", "@forge/ops-queue", "@forge/pay-card", "@forge/pay-invoices"],
}

export default config
