// ┌───────────────────────────────────────────────────────────────────┐
// │ GENERATED BY FORGE — DO NOT EDIT                                   │
// │ capability: kernel.admin@1.0.0                                    │
// │ template:   slots@1.0.0                                           │
// │ Edits are reported by `forge drift` and will conflict on upgrade.  │
// │ customise via the bulkAction, customAdminView, entityDisplayConfig slot(s) instead│
// └───────────────────────────────────────────────────────────────────┘

// Re-exports the slot implementations for kernel.admin.
// The stubs themselves are yours; this index is generated from the
// capability's declared slots and updates when it declares a new one.

export { bulkAction } from './bulkAction.js'
export { customAdminView } from './customAdminView.js'
export { entityDisplayConfig } from './entityDisplayConfig.js'
