// ┌───────────────────────────────────────────────────────────────────┐
// │ GENERATED BY FORGE — DO NOT EDIT                                   │
// │ capability: pay.card@1.0.0                                        │
// │ template:   webhook-route.ts@1.0.0                                │
// │ Edits are reported by `forge drift` and will conflict on upgrade.  │
// │ customise via the afterCharge, beforeCharge, receiptCustomization slot(s) instead│
// └───────────────────────────────────────────────────────────────────┘

import { stripeWebhookHandler } from '@forge/pay-card'
import '@/generated/pay.card/config'

// Signature-verified inside the package: an unsigned or mis-signed payload is
// rejected before it is parsed.
export const POST = stripeWebhookHandler
