// ┌───────────────────────────────────────────────────────────────────┐
// │ GENERATED BY FORGE — DO NOT EDIT                                   │
// │ capability: kernel.identity@1.0.0                                 │
// │ template:   auth-routes.ts@1.0.0                                  │
// │ Edits are reported by `forge drift` and will conflict on upgrade.  │
// │ customise via the onRegistration, passwordPolicy, postLoginRedirect slot(s) instead│
// └───────────────────────────────────────────────────────────────────┘

import { authHandler } from '@forge/kernel-identity'
import * as slots from '@/slots/kernel.identity'

// Mounts the package's auth handler. Configuration only — the implementation
// lives in @forge/kernel-identity and upgrades with its version.
const handler = authHandler({ slots })

export const GET = handler
export const POST = handler
