// ┌───────────────────────────────────────────────────────────────────┐
// │ GENERATED BY FORGE — DO NOT EDIT                                   │
// │ Derived from the manifest and the resolved capability graph.       │
// │ Edits are reported by `forge drift` and will conflict on upgrade.  │
// │ Change the manifest and re-apply, or `forge eject <path>` to take  │
// │ ownership of this file permanently.                                │
// └───────────────────────────────────────────────────────────────────┘

import { createRequire } from 'node:module'
import path from 'node:path'
import { drizzle } from 'drizzle-orm/postgres-js'
import postgres from 'postgres'
import { configureData, runMigrations } from '@forge/kernel-data'

// The data layer has no connection until something gives it one. The runner is
// a standalone script — nothing has booted the app — so it configures the layer
// itself rather than assuming a caller already did.
const url = process.env.DATABASE_URL
if (url === undefined || url === '') {
  console.error('DATABASE_URL is not set. Migrations need a database to run against.')
  process.exit(1)
}

// max: 1 — migrations must run on a single connection, in order. A pool would
// let two migrations interleave and a transaction-scoped lock would not hold
// across them.
const sql = postgres(url, { max: 1 })
configureData({ database: drizzle(sql) })

// Ordered by migration id, which is date-prefixed and immutable once published.
// Every migration ships a rollback; publication fails without one.
const migrations = [
  { capability: "kernel.data", id: "20260601_create_kernel_data", up: "@forge/kernel-data/migrations/20260601_create_kernel_data.up.sql", down: "@forge/kernel-data/migrations/20260601_create_kernel_data.down.sql" },
  { capability: "kernel.identity", id: "20260601_create_kernel_identity", up: "@forge/kernel-identity/migrations/20260601_create_kernel_identity.up.sql", down: "@forge/kernel-identity/migrations/20260601_create_kernel_identity.down.sql" },
  { capability: "kernel.events", id: "20260601_create_kernel_events", up: "@forge/kernel-events/migrations/20260601_create_kernel_events.up.sql", down: "@forge/kernel-events/migrations/20260601_create_kernel_events.down.sql" },
  { capability: "ops.queue", id: "20260701_create_ops_queue", up: "@forge/ops-queue/migrations/20260701_create_ops_queue.up.sql", down: "@forge/ops-queue/migrations/20260701_create_ops_queue.down.sql" },
  { capability: "ops.queue", id: "20260701_upgrade_kernel_work_to_ops_queue", up: "@forge/ops-queue/migrations/20260701_upgrade_kernel_work_to_ops_queue.up.sql", down: "@forge/ops-queue/migrations/20260701_upgrade_kernel_work_to_ops_queue.down.sql" },
  { capability: "data.files", id: "20260701_create_data_files", up: "@forge/data-files/migrations/20260701_create_data_files.up.sql", down: "@forge/data-files/migrations/20260701_create_data_files.down.sql" },
  { capability: "docs.generation", id: "20260701_create_docs_generation", up: "@forge/docs-generation/migrations/20260701_create_docs_generation.up.sql", down: "@forge/docs-generation/migrations/20260701_create_docs_generation.down.sql" },
  { capability: "kernel.access", id: "20260601_create_kernel_access", up: "@forge/kernel-access/migrations/20260601_create_kernel_access.up.sql", down: "@forge/kernel-access/migrations/20260601_create_kernel_access.down.sql" },
  { capability: "kernel.audit", id: "20260601_create_kernel_audit", up: "@forge/kernel-audit/migrations/20260601_create_kernel_audit.up.sql", down: "@forge/kernel-audit/migrations/20260601_create_kernel_audit.down.sql" },
  { capability: "kernel.mail", id: "20260601_create_kernel_mail", up: "@forge/kernel-mail/migrations/20260601_create_kernel_mail.up.sql", down: "@forge/kernel-mail/migrations/20260601_create_kernel_mail.down.sql" },
  { capability: "kernel.money", id: "20260601_create_kernel_money", up: "@forge/kernel-money/migrations/20260601_create_kernel_money.up.sql", down: "@forge/kernel-money/migrations/20260601_create_kernel_money.down.sql" },
  { capability: "pay.card", id: "20260701_create_pay_card", up: "@forge/pay-card/migrations/20260701_create_pay_card.up.sql", down: "@forge/pay-card/migrations/20260701_create_pay_card.down.sql" },
  { capability: "pay.invoices", id: "20260701_create_pay_invoices", up: "@forge/pay-invoices/migrations/20260701_create_pay_invoices.up.sql", down: "@forge/pay-invoices/migrations/20260701_create_pay_invoices.down.sql" },
  { capability: '<client>', id: '0001_client_entities', up: 'migrations/client/0001_client_entities.sql', down: '' },
]

// A migration ships inside its capability's npm package, so its recorded path is
// a package specifier rather than a repo-relative one — it must resolve wherever
// the package is installed, not wherever this script happens to run.
const require = createRequire(import.meta.url)
function resolveMigration(spec: string): string {
  if (!spec.startsWith('@')) return spec
  const [scope, name, ...rest] = spec.split('/')
  const manifest = require.resolve(`${scope}/${name}/package.json`)
  return path.join(path.dirname(manifest), ...rest)
}

const resolved = migrations.map((m) => ({
  ...m,
  up: resolveMigration(m.up),
  down: m.down === '' ? '' : resolveMigration(m.down),
}))

const result = await runMigrations(resolved, { root: process.cwd() })
console.log(`applied ${result.applied.length}, already present ${result.skipped.length}`)
await sql.end()
