// ┌───────────────────────────────────────────────────────────────────┐
// │ GENERATED BY FORGE — DO NOT EDIT                                   │
// │ Derived from the manifest and the resolved capability graph.       │
// │ Edits are reported by `forge drift` and will conflict on upgrade.  │
// │ Change the manifest and re-apply, or `forge eject <path>` to take  │
// │ ownership of this file permanently.                                │
// └───────────────────────────────────────────────────────────────────┘

import { runMigrations } from '@forge/kernel-data'

// Ordered by migration id, which is date-prefixed and immutable once published.
// Every migration ships a rollback; publication fails without one.
const migrations = [
  { capability: "kernel.access", id: "20260601_create_kernel_access", up: "@forge/kernel-access/migrations/20260601_create_kernel_access.up.sql", down: "@forge/kernel-access/migrations/20260601_create_kernel_access.down.sql" },
  { capability: "kernel.audit", id: "20260601_create_kernel_audit", up: "@forge/kernel-audit/migrations/20260601_create_kernel_audit.up.sql", down: "@forge/kernel-audit/migrations/20260601_create_kernel_audit.down.sql" },
  { capability: "kernel.data", id: "20260601_create_kernel_data", up: "@forge/kernel-data/migrations/20260601_create_kernel_data.up.sql", down: "@forge/kernel-data/migrations/20260601_create_kernel_data.down.sql" },
  { capability: "kernel.events", id: "20260601_create_kernel_events", up: "@forge/kernel-events/migrations/20260601_create_kernel_events.up.sql", down: "@forge/kernel-events/migrations/20260601_create_kernel_events.down.sql" },
  { capability: "kernel.identity", id: "20260601_create_kernel_identity", up: "@forge/kernel-identity/migrations/20260601_create_kernel_identity.up.sql", down: "@forge/kernel-identity/migrations/20260601_create_kernel_identity.down.sql" },
  { capability: "kernel.mail", id: "20260601_create_kernel_mail", up: "@forge/kernel-mail/migrations/20260601_create_kernel_mail.up.sql", down: "@forge/kernel-mail/migrations/20260601_create_kernel_mail.down.sql" },
  { capability: "kernel.money", id: "20260601_create_kernel_money", up: "@forge/kernel-money/migrations/20260601_create_kernel_money.up.sql", down: "@forge/kernel-money/migrations/20260601_create_kernel_money.down.sql" },
  { capability: "data.files", id: "20260701_create_data_files", up: "@forge/data-files/migrations/20260701_create_data_files.up.sql", down: "@forge/data-files/migrations/20260701_create_data_files.down.sql" },
  { capability: "docs.generation", id: "20260701_create_docs_generation", up: "@forge/docs-generation/migrations/20260701_create_docs_generation.up.sql", down: "@forge/docs-generation/migrations/20260701_create_docs_generation.down.sql" },
  { capability: "ops.queue", id: "20260701_create_ops_queue", up: "@forge/ops-queue/migrations/20260701_create_ops_queue.up.sql", down: "@forge/ops-queue/migrations/20260701_create_ops_queue.down.sql" },
  { capability: "pay.card", id: "20260701_create_pay_card", up: "@forge/pay-card/migrations/20260701_create_pay_card.up.sql", down: "@forge/pay-card/migrations/20260701_create_pay_card.down.sql" },
  { capability: "pay.invoices", id: "20260701_create_pay_invoices", up: "@forge/pay-invoices/migrations/20260701_create_pay_invoices.up.sql", down: "@forge/pay-invoices/migrations/20260701_create_pay_invoices.down.sql" },
  { capability: "ops.queue", id: "20260701_upgrade_kernel_work_to_ops_queue", up: "@forge/ops-queue/migrations/20260701_upgrade_kernel_work_to_ops_queue.up.sql", down: "@forge/ops-queue/migrations/20260701_upgrade_kernel_work_to_ops_queue.down.sql" },
  { capability: '<client>', id: '0001_client_entities', up: 'migrations/client/0001_client_entities.sql', down: '' },
]

void runMigrations(migrations)
