// ┌───────────────────────────────────────────────────────────────────┐
// │ GENERATED BY FORGE — DO NOT EDIT                                   │
// │ capability: data.files@1.0.0                                      │
// │ template:   slots@1.0.0                                           │
// │ Edits are reported by `forge drift` and will conflict on upgrade.  │
// │ customise via the allowedTypes, processingPipeline, retentionRules, sizeLimits slot(s) instead│
// └───────────────────────────────────────────────────────────────────┘

// Re-exports the slot implementations for data.files.
// The stubs themselves are yours; this index is generated from the
// capability's declared slots and updates when it declares a new one.

export { allowedTypes } from './allowedTypes.js'
export { processingPipeline } from './processingPipeline.js'
export { retentionRules } from './retentionRules.js'
export { sizeLimits } from './sizeLimits.js'
