// ┌───────────────────────────────────────────────────────────────────┐
// │ GENERATED BY FORGE — DO NOT EDIT                                   │
// │ capability: pay.card@1.0.0                                        │
// │ template:   slots@1.0.0                                           │
// │ Edits are reported by `forge drift` and will conflict on upgrade.  │
// │ customise via the afterCharge, beforeCharge, receiptCustomization slot(s) instead│
// └───────────────────────────────────────────────────────────────────┘

// Re-exports the slot implementations for pay.card.
// The stubs themselves are yours; this index is generated from the
// capability's declared slots and updates when it declares a new one.

export { afterCharge } from './afterCharge.js'
export { beforeCharge } from './beforeCharge.js'
export { receiptCustomization } from './receiptCustomization.js'
