// ┌───────────────────────────────────────────────────────────────────┐
// │ GENERATED BY FORGE — DO NOT EDIT                                   │
// │ capability: docs.generation@1.0.0                                 │
// │ template:   slots@1.0.0                                           │
// │ Edits are reported by `forge drift` and will conflict on upgrade.  │
// │ customise via the brandingOverride, outputFormats, templateHelpers slot(s) instead│
// └───────────────────────────────────────────────────────────────────┘

// Re-exports the slot implementations for docs.generation.
// The stubs themselves are yours; this index is generated from the
// capability's declared slots and updates when it declares a new one.

export { brandingOverride } from './brandingOverride.js'
export { outputFormats } from './outputFormats.js'
export { templateHelpers } from './templateHelpers.js'
