// ┌───────────────────────────────────────────────────────────────────┐
// │ GENERATED BY FORGE — DO NOT EDIT                                   │
// │ capability: kernel.observability@1.0.0                            │
// │ template:   instrumentation.ts@1.0.0                              │
// │ Edits are reported by `forge drift` and will conflict on upgrade.  │
// │ eject it with `forge eject` if it must diverge                    │
// └───────────────────────────────────────────────────────────────────┘

export async function register() {
  const { initObservability } = await import('@forge/kernel-observability')
  await initObservability({ product: "reference", environment: "development" })
}
