package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/originplatformlabs/forge/internal/catalog"
	"github.com/originplatformlabs/forge/internal/manifest"
	"github.com/originplatformlabs/forge/internal/plan"
	"github.com/originplatformlabs/forge/internal/resolve"
	"github.com/originplatformlabs/forge/internal/state"
)

// cmdInit scaffolds a manifest. It writes exactly one file and refuses to
// overwrite an existing one: a command that can clobber a manifest is a command
// nobody runs twice.
func cmdInit(args []string) int {
	fs := flag.NewFlagSet("init", flag.ContinueOnError)
	var target, product, client, caps string
	fs.StringVar(&target, "target-dir", ".", "directory to scaffold into")
	fs.StringVar(&product, "product", "", "product slug, e.g. acme-restoration")
	fs.StringVar(&client, "client", "", "client legal name")
	fs.StringVar(&caps, "capabilities", "", "comma-separated capability ids")
	c := parseCommon(fs, args)

	if product == "" {
		fmt.Fprintln(os.Stderr, "error: --product is required")
		fmt.Fprintln(os.Stderr, "fix: forge init --product acme-restoration --client \"Acme Restoration LLC\"")
		return 1
	}
	if client == "" {
		client = product
	}

	out := filepath.Join(target, "forge.yaml")
	if _, err := os.Stat(out); err == nil {
		fmt.Fprintf(os.Stderr, "error: %s already exists\n", out)
		fmt.Fprintln(os.Stderr, "fix: edit it directly, or run init against an empty directory")
		return 1
	}
	if err := os.MkdirAll(target, 0o755); err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		return 1
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# %s — generated by `forge init`.\n", product)
	fmt.Fprintf(&b, "# This is the only file a human edits during routine onboarding.\n")
	fmt.Fprintf(&b, "manifest_version: 1\n\n")
	fmt.Fprintf(&b, "catalog:\n  snapshot: \"2026-07-15\"\n\n")
	fmt.Fprintf(&b, "product:\n  id: %s\n  name: %s\n  client:\n    name: %s\n    legal_entity: %s\n\n",
		product, product, client, client)

	fmt.Fprintf(&b, "# The kernel is mandatory and implicit — never list it here.\n")
	fmt.Fprintf(&b, "# Hard dependencies resolve automatically; `forge graph` shows what gets added.\n")
	fmt.Fprintf(&b, "capabilities:\n")
	if strings.TrimSpace(caps) == "" {
		fmt.Fprintf(&b, "  []\n")
	} else {
		for _, id := range strings.Split(caps, ",") {
			fmt.Fprintf(&b, "  - id: %s\n", strings.TrimSpace(id))
		}
	}

	// Derive the credential bindings the selected capabilities actually need,
	// including those pulled in transitively. Making the operator discover six
	// credential names by trial and error is the friction the one-hour
	// onboarding target cannot afford — and the specifications already know.
	fmt.Fprintf(&b, "\n# Credentials are NAMES, never values. `forge validate` checks presence\n")
	fmt.Fprintf(&b, "# only; `forge apply` resolves them in memory and never writes them anywhere.\n")
	fmt.Fprintf(&b, "integrations:\n")
	needed := requiredCredentials(c, product, caps)
	if len(needed) == 0 {
		fmt.Fprintf(&b, "  {}\n")
	}
	for _, svc := range needed {
		fmt.Fprintf(&b, "  %s:\n    credentials:\n", svc.slug)
		for _, cred := range svc.creds {
			fmt.Fprintf(&b, "      %s: { secret_ref: %s/%s }  # %s\n",
				cred, product, strings.ToLower(cred), svc.capability)
		}
	}
	fmt.Fprintf(&b, "\nenvironments:\n  development:\n    provider: local\n    secrets:\n      provider: file\n      path: .forge/secrets.json\n")

	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		return 1
	}

	fmt.Printf("Created %s\n\n", out)
	fmt.Printf("Next:\n")
	fmt.Printf("  forge catalog -C %s              browse what you can add\n", c.root)
	fmt.Printf("  forge validate -C %s -f %s\n", c.root, out)
	fmt.Printf("  forge plan -C %s -f %s --target-dir %s\n", c.root, out, target)
	return 0
}

// cmdDrift reports hand-edits to generated files. Read-only.
func cmdDrift(args []string) int {
	fs := flag.NewFlagSet("drift", flag.ContinueOnError)
	var target, env string
	fs.StringVar(&target, "target-dir", ".", "client repository to inspect")
	fs.StringVar(&env, "env", "", "environment (default: development)")
	c := parseCommon(fs, args)

	p, code := build(c, target, env)
	if code != 0 {
		return code
	}
	pl, err := plan.Compute(target, p.st, p.desired)
	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		return 1
	}

	n := 0
	for _, a := range pl.Actions {
		if a.Verb != plan.Drift {
			continue
		}
		if n == 0 {
			fmt.Printf("Hand-edited generated files in %s\n\n", pl.Workspace)
		}
		n++
		fmt.Printf("  %s\n    capability: %s, template: %s\n", a.Path, a.Capability, a.Template)
	}

	for _, e := range p.st.Ejected {
		fmt.Printf("\n  %s (ejected)\n    released at %s; receives no further upgrades for this file\n    reason: %s\n",
			e.Path, e.EjectedAtCapabilityVersion, e.Reason)
	}

	if n == 0 {
		fmt.Printf("No drift. Every managed file in %s is what Forge wrote.\n", pl.Workspace)
		return 0
	}
	fmt.Printf("\n%d drifted file(s).\n", n)
	fmt.Println("`forge eject <path> --reason \"...\"` keeps the edit and stops managing the file.")
	fmt.Println("`forge apply --accept-drift` discards the edit and restores the generated content.")
	return 2
}

// cmdEject releases one file from management, per-file and recorded in state.
//
// Whole-project ejection is the create-react-app mistake: a one-way door that
// costs you every future upgrade. Here the rest of the product keeps upgrading
// normally and `forge fleet status` can report where the fleet is fragmenting.
func cmdEject(args []string) int {
	if len(args) < 1 || strings.HasPrefix(args[0], "-") {
		fmt.Fprintln(os.Stderr, "error: forge eject <path> --reason \"why\"")
		return 2
	}
	path := args[0]

	fs := flag.NewFlagSet("eject", flag.ContinueOnError)
	var target, env, reason string
	fs.StringVar(&target, "target-dir", ".", "client repository")
	fs.StringVar(&env, "env", "", "environment (default: development)")
	fs.StringVar(&reason, "reason", "", "why this file must diverge")
	c := parseCommon(fs, args[1:])

	if reason == "" {
		fmt.Fprintln(os.Stderr, "error: --reason is required")
		fmt.Fprintln(os.Stderr, "fix: an ejected file stops receiving upgrades; the reason is what makes that reviewable later")
		return 1
	}

	p, code := build(c, target, env)
	if code != 0 {
		return code
	}

	tracked, ok := p.st.FileByPath(path)
	if !ok {
		fmt.Fprintf(os.Stderr, "error: %s is not a file Forge manages\n", path)
		fmt.Fprintln(os.Stderr, "fix: run `forge plan` to see managed paths")
		return 1
	}
	if p.st.IsEjected(path) {
		fmt.Printf("%s is already ejected.\n", path)
		return 0
	}

	capVersion := ""
	for _, n := range p.g.All() {
		if n.Cap.ID == tracked.Capability {
			capVersion = n.Cap.Version
		}
	}

	prior := p.st.Serial
	p.st.Ejected = append(p.st.Ejected, state.Ejected{
		Path:                       path,
		EjectedFromTemplate:        tracked.Template + "@" + tracked.TemplateVersion,
		EjectedAtCapabilityVersion: capVersion,
		Reason:                     reason,
	})
	p.st.RemoveFile(path)
	p.st.Serial++

	if err := state.Save(target, p.st, prior); err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		return 1
	}

	fmt.Printf("Ejected %s\n\n", path)
	fmt.Printf("  It keeps your edits and Forge will not touch it again.\n")
	fmt.Printf("  Lost: upgrades, bug fixes, and security patches to %s's %s template.\n",
		tracked.Capability, tracked.Template)
	fmt.Printf("  Everything else in this product continues to upgrade normally.\n")
	return 0
}

type serviceCreds struct {
	slug       string
	capability string
	creds      []string
}

// requiredCredentials resolves the selected capability set and returns every
// non-optional credential it declares, grouped by service. Transitive
// dependencies are included, because those are exactly the ones an operator
// would not think to look for.
func requiredCredentials(c *commonFlags, product, caps string) []serviceCreds {
	cat, ds, err := catalog.Load(c.catalogDir(), c.capSchema())
	if err != nil || ds.HasErrors() {
		return nil
	}

	m := &manifest.Manifest{
		ManifestVersion: 1,
		Catalog:         manifest.CatalogPin{Snapshot: "2026-07-15"},
		Product:         manifest.Product{ID: product, Name: product},
		SourceFile:      "<init>",
	}
	for _, id := range strings.Split(caps, ",") {
		if id = strings.TrimSpace(id); id != "" {
			m.Capabilities = append(m.Capabilities, manifest.Selection{ID: id})
		}
	}

	g, _ := resolve.Resolve(m, cat)

	bySlug := map[string]*serviceCreds{}
	var order []string
	for _, n := range g.Active() {
		for _, ext := range n.Cap.External {
			if ext.Optional {
				continue
			}
			slug := serviceSlug(ext.Service)
			if _, ok := bySlug[slug]; !ok {
				bySlug[slug] = &serviceCreds{slug: slug, capability: n.Cap.ID}
				order = append(order, slug)
			}
			for _, cred := range ext.Credentials {
				if !cred.Optional {
					bySlug[slug].creds = append(bySlug[slug].creds, cred.Name)
				}
			}
		}
	}

	sort.Strings(order)
	out := make([]serviceCreds, 0, len(order))
	for _, slug := range order {
		sc := bySlug[slug]
		if len(sc.creds) == 0 {
			continue
		}
		sort.Strings(sc.creds)
		out = append(out, *sc)
	}
	return out
}

func serviceSlug(service string) string {
	s := strings.ToLower(service)
	for _, cut := range []string{" or ", " and ", ","} {
		if i := strings.Index(s, cut); i > 0 {
			s = s[:i]
		}
	}
	s = strings.Map(func(r rune) rune {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			return r
		}
		return '_'
	}, strings.TrimSpace(s))
	for strings.Contains(s, "__") {
		s = strings.ReplaceAll(s, "__", "_")
	}
	return strings.Trim(s, "_")
}
