// ┌───────────────────────────────────────────────────────────────────┐
// │ GENERATED BY FORGE — DO NOT EDIT                                   │
// │ capability: kernel.identity@1.0.0                                 │
// │ template:   slots@1.0.0                                           │
// │ Edits are reported by `forge drift` and will conflict on upgrade.  │
// │ customise via the onRegistration, passwordPolicy, postLoginRedirect slot(s) instead│
// └───────────────────────────────────────────────────────────────────┘

// Re-exports the slot implementations for kernel.identity.
// The stubs themselves are yours; this index is generated from the
// capability's declared slots and updates when it declares a new one.

export { onRegistration } from './onRegistration.js'
export { passwordPolicy } from './passwordPolicy.js'
export { postLoginRedirect } from './postLoginRedirect.js'
